server: 
g++ ./server.cpp ./commoncode.cpp ./DES.cpp  -o server.o

client: 
g++ ./client.cpp ./commoncode.cpp ./DES.cpp  -o client.o

clean:
rm *.o

start server:
./server.o 

start client:
./client.o
